POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

test@example.com
------FormBoundary1234

### Get all photos
GET http://localhost:3000/api/photos HTTP/1.1

### Get single photo
GET http://localhost:3000/api/photos/1749727232308 HTTP/1.1

### Delete photo
DELETE http://localhost:3000/api/photos/1749727767597 HTTP/1.1

### Update photo status
PATCH http://localhost:3000/api/photos HTTP/1.1
Content-Type: application/json

{
  "id": 1749727719576,
  "status": "changed 2nd time"
}

### Add tags to photo
PATCH http://localhost:3000/api/photos/tags HTTP/1.1
Content-Type: application/json

{
  "photoId": 1750089731361,
  "tags": [
    {
      "name": "#nowytagdlazdjęciaasdasd"
    }
  ]
}

### Add multiple tags to photo
PATCH http://localhost:3000/api/photos/tags HTTP/1.1
Content-Type: application/json

{
  "photoId": 1749727832443,
  "tags": [
    {
      "name": "#nowytag1dlazdjęcia"
    },
    {
      "name": "#nowytag2dlazdjęcia"
    },
    {
      "name": "#nowytag3dlazdjęcia"
    }
  ]
}

### Get tags for specific photo
GET http://localhost:3000/api/photos/tags/1749727832443 HTTP/1.1

