GET http://localhost:3000/api/profile
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3NTAxMjA4ODc5MjEsImVtYWlsIjoidGVzdDVAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTAxMjA5NDIsImV4cCI6MTc1MDEyNDU0Mn0.3P2F0jJO9mZ0i5WYi2Ii5ZYdHz2cGd70NPrNu2ihCQU
###
PATCH http://localhost:3000/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3NDk3Mjg4MjcwMjIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDk3Mjg4NDEsImV4cCI6MTc0OTczMjQ0MX0.O1Boxd0WkJy66dphiVE2xOg4UOlGZsocDRqlC37kZBs

{
  "name": "New Name",
  "lastName": "New Lastname"
}
###
POST http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3NTAxMjA4ODc5MjEsImVtYWlsIjoidGVzdDVAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTAxMjA5NDIsImV4cCI6MTc1MDEyNDU0Mn0.3P2F0jJO9mZ0i5WYi2Ii5ZYdHz2cGd70NPrNu2ihCQU
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="user.png"
Content-Type: image/png

< ./user.png

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

test@example.com
------FormBoundary1234
###
GET http://localhost:3000/api/profile/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3NDk3NTM0OTE3NjEsImVtYWlsIjoidGVzdDVAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDk3NTM0OTEsImV4cCI6MTc0OTc1NzA5MX0.QIcCEEvPPJhHG4MNWxpKWoP70EnjLSd8RebfZ7AR_rU